### ISSUE TITLE
SealYun

### ISSUE THREAD

**Issue by fanux** [fanux/gitalk#1]
http://store.lameleg.com

**Comment by fanux** [comment]
欢迎大家使用

**Comment by fanux** [comment]
建议，吐槽，好评，投诉，或者有什么需要咨询的，都可在此评论。 欢迎大家使用我们的离线包，感谢大家对付费的支持。

  QQ群：98488045

  开源项目： 
      * [lhttp](https://github.com/fanux/lhttp)  golang websocket框架，轻量级及时通信服务
      * [sealos](https://github.com/fanux/sealos) kubernetes轻量级高可用安装
      * [fist](https://github.com/fanux/fist) kubernetes token生成管理等（可用于dashboard token登录等）

**Comment by dotiao** [comment]
支持外部的etcd集群吗？

**Comment by fanux** [comment]
> @dotiao
> 支持外部的etcd集群吗？

支持，安装时要修改配置
```
etcd:
    external:
        caFile: /etc/kubernetes/pki/cfssl/ca.pem
        certFile: /etc/kubernetes/pki/cfssl/client.pem
        keyFile: /etc/kubernetes/pki/cfssl/client-key.pem
        endpoints:
        - https://10.1.86.204:2379
        - https://10.1.86.205:2379
        - https://10.1.86.206:2379
```
